### ISSUE TITLE
ZeroDivisionError with vFuse recipe generation

### ISSUE THREAD

**Issue by discentem** [homebysix/recipe-robot#124]
Here's the url I used: https://github.com/chilcote/vfuse

And the output:
```python [ERROR] Recipe Robot exploded with unexpected error: integer division or modulo by zero
Traceback (most recent call last):
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe-robot", line 95, in main
    process_input_path(facts)
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/inspect.py", line 131, in process_input_path
    facts = inspect_func(input_path, args, facts)
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/inspect.py", line 1209, in inspect_github_url
    facts = inspect_download_url(download_url, args, facts)
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/inspect.py", line 979, in inspect_download_url
    if (file_size_dl / block_sz) % (file_size / block_sz / 10) == 0:
ZeroDivisionError: integer division or modulo by zero

**Comment by homebysix** [comment]
Hi @discentem,

Although I'm a big fan of vfuse, it's a command-line tool, not a native Mac app, and therefore out of the scope of what Recipe Robot supports.
