### ISSUE TITLE
Unexpected error: RecipeIdentifierPrefix

### ISSUE THREAD

**Issue by qu1gl3s** [homebysix/recipe-robot#130]
Hi,

I'm running the latest version of Recipe Robot, 1.0.5 on macOS 10.13.4. I'm using the script to use the --ignore-existing flag for this application.

I'm attempting to build a recipe for EnzymeX with the download link: http://downloads.nucleobytes.com/enzymex.dmg

The error I receive is below:

`[ERROR] Recipe Robot exploded with unexpected error: RecipeIdentifierPrefix
Traceback (most recent call last):
  File "./recipe-robot", line 98, in main
    time, _ = recipe_robot_lib.generate_recipes(facts, prefs)  # pylint: disable=assignment-from-no-return
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/tools.py", line 117, in run_func
    result = func(*args, **kwargs)
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/recipe_generator.py", line 102, in generate_recipes
    build_recipes(facts, preferred, prefs)
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/recipe_generator.py", line 157, in build_recipes
    keys["Identifier"] = "%s.%s.%s" % (prefs["RecipeIdentifierPrefix"],
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 162, in __getitem__objectForKey_
    return container_unwrap(res, KeyError, key)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 659, in container_unwrap
    raise exc_type(*exc_args)
KeyError: 'RecipeIdentifierPrefix'`

Any assistance would be appreciated.

**Comment by qu1gl3s** [comment]
I was an idiot and didn't configure RR correctly on first install.

It is now working perfectly. Closing this as this is no longer an issue.

For those who have this issue, configure the settings in the app or use the `recipe-robot --config` and follow the prompts.
