### ISSUE TITLE
Error when creating recipes

### ISSUE THREAD

**Issue by apizz** [homebysix/recipe-robot#159]
**Describe the bug**
Error produced when trying to create recipes for Asset Catalog Tinkerer.  Output:

```
Processing: https://github.com/insidegui/AssetCatalogTinkerer/releases/download/2.5.1/AssetCatalogTinkerer_v2.5.1.zip
Input path looks like a GitHub URL.
[WARNING] I'm processing the input path as a GitHub repo URL, but you may have wanted me to treat it as a download URL.
Getting GitHub repo...
    GitHub repo is: insidegui/AssetCatalogTinkerer
Getting app name...
    App name is: AssetCatalogTinkerer
Getting GitHub description...
    GitHub description is: An app that lets you open .car files and browse/extract their images.
Getting information from latest GitHub release...
    GitHub release download format is: zip
    GitHub release download URL is: https://github.com/insidegui/AssetCatalogTinkerer/releases/download/2.5.1/AssetCatalogTinkerer_v2.5.1.zip
    Download URL is: https://github.com/insidegui/AssetCatalogTinkerer/releases/download/2.5.1/AssetCatalogTinkerer_v2.5.1.zip
Downloading file for further inspection...
    10%
    20%
    30%
    40%
    50%
    60%
    70%
    80%
    90%
    100%
    Downloaded to /Users/ap.orlebeke/Library/Caches/Recipe Robot/2020-04-28_10-41-58_692861/AssetCatalogTinkerer_v2.5.1.zip
Determining download format...
    File extension is zip
Opening downloaded file...
    Successfully unarchived zip
Validating app...
    This app seems valid
Getting bundle name...
    Bundle name is: Asset Catalog Tinkerer
Getting bundle identifier...
    Bundle identifier is: br.com.guilhermerambo.Asset-Catalog-Tinkerer
Checking for a Sparkle feed...
    Sparkle feed is: https://github.com/insidegui/AssetCatalogTinkerer/raw/master/releases/appcast.xml
Getting information from Sparkle feed...
    The Sparkle feed provides a version number
    The latest version is 251
    Download URL is: https://github.com/insidegui/AssetCatalogTinkerer/releases/download/2.5/AssetCatalogTinkerer_v2.5.zip
Downloading file for further inspection...
    10%
    20%
    29%
    39%
    49%
    59%
    69%
    79%
    88%
    98%
    Downloaded to /Users/ap.orlebeke/Library/Caches/Recipe Robot/2020-04-28_10-41-58_692861/AssetCatalogTinkerer_v2.5.zip
Determining download format...
    File extension is zip
Looking for version key...
    Version key is: CFBundleShortVersionString (2.5.1)
Looking for icon...
    Icon is: /Users/ap.orlebeke/Library/Caches/Recipe Robot/2020-04-28_10-41-58_692861/unpacked/Asset Catalog Tinkerer.app/Contents/Resources/AppIcon
Gathering code signature information...
    Code signature verification requirements recorded
    3 authority names recorded
    Developer: GUILHERME RAMBO
Searching for existing AutoPkg recipes for Asset+Catalog+Tinkerer...
    No results
Searching for existing AutoPkg recipes for AssetCatalogTinkerer...
    No results
[ERROR] Recipe Robot exploded with unexpected error: RecipeIdentifierPrefix
Traceback (most recent call last):
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe-robot", line 90, in main
    time, _ = recipe_robot_lib.generate_recipes(facts, prefs)
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/tools.py", line 138, in run_func
    result = func(*args, **kwargs)
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/recipe_generator.py", line 115, in generate_recipes
    build_recipes(facts, preferred, prefs)
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/recipe_generator.py", line 179, in build_recipes
    prefs["RecipeIdentifierPrefix"],
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 162, in __getitem__objectForKey_
    return container_unwrap(res, KeyError, key)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 659, in container_unwrap
    raise exc_type(*exc_args)
KeyError: 'RecipeIdentifierPrefix'

[ERROR] 
```

**To Reproduce**
1. Go to Asset Catalog Tinkerer repo
2. Copy link to latest asset
3. Paste in Recipe Robot
4. Let process and see error

**Expected behavior**
Create recipes

**Screenshots**

**Desktop (please complete the following information):**
 - macOS: **10.14.6**
 - Recipe Robot Version: **1.2.1**
 - `which python`:  **/usr/bin/python**
 - `python --version`: **Python 2.7.10**

**Additional context**

**Comment by apizz** [comment]
Ultimately was able to create the needed recipes, so just wanted to report

**Comment by homebysix** [comment]
`KeyError: 'RecipeIdentifierPrefix'` usually means you haven't configured Recipe Robot yet. In the command-line you can run `recipe-robot --config` to do this. In the Mac app, the config options should appear at first launch, or you can click the ⚙️ icon. The "preferred recipe identifier" is the missing preference.

Let me know whether that solves it for you.

**Comment by apizz** [comment]
Strange, because when I originally opened the app it did present me the initial prompt to configure the desired recipes.  Running the config command and reconfirming everything worked for me.

Thanks!
