### ISSUE TITLE
Issues Creating recipes for RingCentral Phone and RingCentral Meetings

### ISSUE THREAD

**Issue by Alex-Addepar** [homebysix/recipe-robot#166]
I'm currently running autopkg 2.1 w/ jssimporter

Ringcentral phone - URL - https://downloads.ringcentral.com/sp/RingCentralForMac

Traceback - note I get the same error when trying from the app itself

`:~$ recipe-robot --verbose https://downloads.ringcentral.com/sp/RingCentralForMac                                                  Thu Sep 24 17:45:08 2020
Traceback (most recent call last):
  File "/usr/local/bin/recipe-robot", line 42, in <module>
    import recipe_robot_lib
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/__init__.py", line 26, in <module>
    from .recipe_generator import generate_recipes
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/recipe_generator.py", line 34, in <module>
    from . import processor
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/processor.py", line 38, in <module>
    import autopkglib
  File "/Library/AutoPkg/autopkglib/__init__.py", line 186
    raise PreferenceError(f"Could not synchronize preference {key}")`

Ringcentral meetings - URL - http://dn.ringcentral.com/data/web/download/RCMeetings/1210/RCMeetingsClientSetup.pkg

Traceback - also get the same error from the app itself

`~$ recipe-robot --verbose http://dn.ringcentral.com/data/web/download/RCMeetings/1210/RCMeetingsClientSetup.pkg          2042ms  Thu Sep 24 17:53:23 2020
Traceback (most recent call last):
  File "/usr/local/bin/recipe-robot", line 42, in <module>
    import recipe_robot_lib
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/__init__.py", line 26, in <module>
    from .recipe_generator import generate_recipes
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/recipe_generator.py", line 34, in <module>
    from . import processor
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/processor.py", line 38, in <module>
    import autopkglib
  File "/Library/AutoPkg/autopkglib/__init__.py", line 186
    raise PreferenceError(f"Could not synchronize preference {key}")`

**Comment by homebysix** [comment]
@Alex-Addepar What version of Recipe Robot are you using?

Recipe Robot 1.x requires AutoPkg 1.x. A new version that supports AutoPkg 2.x is coming soon, and you can test it early by checking out the [2.0.0-dev branch](https://github.com/homebysix/recipe-robot/tree/2.0.0-dev) now.

**Comment by Alex-Addepar** [comment]
I'm using the latest release but that explains a lot. I can definitely try the dev branch anything I need to know?

**Comment by homebysix** [comment]
The 2.0.0 release is coming soon, so if you would prefer not to mess with git branches, you could wait a week or so.
