### ISSUE TITLE
Failed creation error

### ISSUE THREAD

**Issue by mrpeanutbutter** [homebysix/recipe-robot#88]
Not sure if this is expected behavior but just wanted to provide some feedback/FYI.

This was for the using the url http://www.parallels.com/directdownload/pd11

Sidenote: ( I am now aware of your recipe for parallels. Thank you! ) 

[ERROR] Recipe Robot exploded with unexpected error: RecipeCreateLocation
Traceback (most recent call last):
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe-robot", line 104, in main
    time, _ = recipe_robot_lib.generate_recipes(facts, prefs)  # pylint: disable=assignment-from-no-return
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/tools.py", line 111, in run_func
    result = func(*args, **kwargs)
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/recipe_generator.py", line 99, in generate_recipes
    recipe_dest_dir = robo_join(prefs["RecipeCreateLocation"],
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 162, in __getitem__objectForKey_
    return container_unwrap(res, KeyError, key)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 659, in container_unwrap
    raise exc_type(*exc_args)
KeyError: 'RecipeCreateLocation'

[ERROR]

**Comment by homebysix** [comment]
Looks like the same issue as #80, which we're working on.

**Comment by homebysix** [comment]
Additionally, Parallels will fail even after this bug gets fixed, because its dmg includes an installer app.

![screen shot 2015-12-08 at 3 37 04 pm](https://cloud.githubusercontent.com/assets/7801391/11672030/a02d9114-9dc1-11e5-99c9-902cc50251af.png)

Recipe Robot's default behavior will be to create a recipe that simply places this app into the Applications folder, which in this case is the wrong behavior. The recipes available [here](https://github.com/autopkg/homebysix-recipes/tree/master/Parallels) take that into account.
